---
- name: Set git_username if not defined
  become: false
  set_fact:
    git_username: "{{ local_user_fullname }}"
  when: git_username is not defined

- name: Install Git (Ubuntu)
  become: true
  apt:
    pkg:
      - git
    state: present
  when:
    - ansible_facts['distribution'] == "Ubuntu"

- name: Install Diff Tool (Ubuntu)
  become: true
  apt:
    pkg:
      - meld
    state: present
  when:
    - git_install_meld
    - ansible_facts['distribution'] == "Ubuntu"

- name: Configure Git
  become: false
  template:
    src: gitconfig.j2
    dest: "{{ local_user_homedir }}/.gitconfig"
    mode: 0644

- name: Configure Global gitignore
  become: false
  template:
    src: gitignore_global.j2
    dest: "{{ local_user_homedir }}/.gitignore_global"
    mode: 0644

